services:
  db:
    image: postgres:16
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
    container_name: loanflow-db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5433:5432
  
  redis:
    image: redis:7
    container_name: loanflow-redis
    restart: always
    ports:
      - 6379:6379

  http:
    build: .
    container_name: loanflow
    ports:
      - 8080:8000
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DATABASE=postgres
      - SQL_HOST=db
      - SQL_PORT=5432
    command: python3 manage.py runserver 0.0.0.0:8000

  celery:
    build: .
    container_name: loanflow-celery
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A loanflow worker --loglevel=info

volumes:
  data: